name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
  release:

permissions:
  contents: read


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Clean compile and run tests
        run: sbt clean test test-int:test test-perf:test
