name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  release:

permissions:
  contents: read


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Clean compile
        run: sbt clean

      - name: Run fast tests
        run: sbt test

#      - name: Run slow tests
#        run: sbt test-slow:test
